jobs:
  build:
    docker:
      - image: python:3.6                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: |                              # similar to "script" in GitLab
          pip install -r requirements.txt
          python manage.py check

  test:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: |
          pip install -r requirements.txt
          python manage.py test taskManager

  semgrep:
    docker:
      - image: returntocorp/semgrep-agent:v1
    environment:
      SEMGREP_RULES: >- # more at semgrep.dev/explore
        p/security-audit
        p/secrets
        p/django

    steps:
      - checkout

      - run:
          name: "Semgrep scan"
          command: semgrep-agent --gitlab-json > semgrep-output.json

      - store_artifacts:
          path: semgrep-output.json
          destination: semgrep-artifact

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  django:
    jobs:
      - build
      - test:
          requires:
            - build 
      - integration:
          requires:
            - test
      - prod:
          type: approval
          requires:
            - integration
